extends Node3D

@export var terrain_manager: Node3D

var tree_mesh: Mesh
var vegetation_multimesh: MultiMeshInstance3D

func _ready():
	# Create a simple placeholder mesh for the tree
	tree_mesh = create_basic_tree_mesh()
	
	vegetation_multimesh = MultiMeshInstance3D.new()
	vegetation_multimesh.multimesh = MultiMesh.new()
	
	# Initial setup, will be updated by chunks
	vegetation_multimesh.multimesh.mesh = tree_mesh
	vegetation_multimesh.multimesh.transform_format = MultiMesh.TRANSFORM_3D
	# Max instances will be set dynamically or to a large enough value
	vegetation_multimesh.multimesh.instance_count = 0 
	
	add_child(vegetation_multimesh)

func create_basic_tree_mesh() -> Mesh:
	var st = SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	
	# Trunk (Cylinder)
	var trunk_mat = StandardMaterial3D.new()
	trunk_mat.albedo_color = Color(0.5, 0.2, 0.0)
	st.set_material(trunk_mat)
	
	var trunk_height = 5.0
	var trunk_radius = 0.5
	
	# Add cylinder (simple version for placeholder)
	for i in range(16):
		var angle1 = float(i) / 16.0 * PI * 2.0
		var angle2 = float(i+1) / 16.0 * PI * 2.0
		var p1 = Vector3(cos(angle1) * trunk_radius, 0, sin(angle1) * trunk_radius)
		var p2 = Vector3(cos(angle2) * trunk_radius, 0, sin(angle2) * trunk_radius)
		var p3 = Vector3(cos(angle2) * trunk_radius, trunk_height, sin(angle2) * trunk_radius)
		var p4 = Vector3(cos(angle1) * trunk_radius, trunk_height, sin(angle1) * trunk_radius)
		
		# Bottom face
		st.add_vertex(p1)
		st.add_vertex(p2)
		st.add_vertex(Vector3(0,0,0))
		
		# Top face
		st.add_vertex(p3)
		st.add_vertex(p4)
		st.add_vertex(Vector3(0,trunk_height,0))
		
		# Side faces
		st.add_vertex(p1)
		st.add_vertex(p2)
		st.add_vertex(p3)
		st.add_vertex(p1)
		st.add_vertex(p3)
		st.add_vertex(p4)
	
	# Leaves (Cone)
	var leaves_mat = StandardMaterial3D.new()
	leaves_mat.albedo_color = Color(0.0, 0.5, 0.1)
	st.set_material(leaves_mat)
	
	var leaves_height = 7.0
	var leaves_radius = 3.0
	var leaves_base_y = trunk_height * 0.8
	
	# Add cone (simple version)
	for i in range(16):
		var angle1 = float(i) / 16.0 * PI * 2.0
		var angle2 = float(i+1) / 16.0 * PI * 2.0
		var p1 = Vector3(cos(angle1) * leaves_radius, leaves_base_y, sin(angle1) * leaves_radius)
		var p2 = Vector3(cos(angle2) * leaves_radius, leaves_base_y, sin(angle2) * leaves_radius)
		var p_top = Vector3(0, leaves_base_y + leaves_height, 0)
		
		st.add_vertex(p1)
		st.add_vertex(p2)
		st.add_vertex(p_top)
	
	# For simplicity, just commit. Normals will be autogenerated roughly.
	return st.commit()

func add_tree_instance(global_transform: Transform3D):
	# Add a single instance.
	# This needs to be batched or handled with MultiMesh.instance_count += 1
	# For now, just placeholder. Actual implementation will be more complex (MultiMesh per chunk)
	pass # Actual MultiMesh code will go here later
